# Generated by Django 5.2.8 on 2026-03-28 21:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('applicant', 'Applicant'), ('representative', 'Company Representative'), ('admin', 'Administrator')], default='applicant', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/%d/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.FileField(help_text='Upload your CV (PDF or DOCX)', upload_to='cvs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('summary', models.TextField(blank=True, help_text='Professional summary or bio')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Expected annual salary', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location_preference', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'applicant'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Official company name', max_length=150, unique=True)),
                ('location', models.CharField(help_text='Headquarters location', max_length=150)),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('description', models.TextField(blank=True, help_text='Company description and mission')),
                ('industry', models.CharField(blank=True, help_text='Primary industry (e.g., Technology, Healthcare)', max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, help_text='Number of employees', null=True, verbose_name='Company Size')),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the company is currently active on the platform')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='recruiter_c_name_506e9c_idx'), models.Index(fields=['industry'], name='recruiter_c_industr_e0a14a_idx'), models.Index(fields=['is_active'], name='recruiter_c_is_acti_ffe16a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(choices=[('job', 'Job Position'), ('project', 'Project')], db_index=True, max_length=20)),
                ('title', models.CharField(help_text='Title of the job or project', max_length=250)),
                ('description', models.TextField(help_text='Detailed description')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary for jobs', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for projects', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('filled', 'Filled/Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='recruiter.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField(help_text='Comment content')),
                ('is_edited', models.BooleanField(default=False)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recruiter.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recruiter.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Job Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], db_index=True, default='applied', max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter for the job application')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Your expected salary for this position', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruiter.applicantprofile')),
                ('job', models.ForeignKey(limit_choices_to={'post_type': 'job', 'status': 'published'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruiter.post')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(help_text='Position at the company (e.g., HR Manager, Tech Lead)', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for the company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='recruiter.company')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'representative'}, on_delete=django.db.models.deletion.CASCADE, related_name='representative_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bid amount for the project', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proposal Amount')),
                ('description', models.TextField(help_text='Detailed proposal description')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('cover_letter', models.FileField(blank=True, help_text='Optional cover letter (PDF)', null=True, upload_to='proposals/%Y/%m/%d/')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in days', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='recruiter.applicantprofile')),
                ('project', models.ForeignKey(limit_choices_to={'post_type': 'project', 'status': 'published'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='recruiter.post')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to='recruiter.representativeprofile')),
            ],
            options={
                'ordering': ['amount', '-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to='recruiter.representativeprofile'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Skill name (e.g., Python, React, Project Management)', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('business', 'Business'), ('marketing', 'Marketing'), ('data', 'Data Science'), ('devops', 'DevOps'), ('soft', 'Soft Skills'), ('other', 'Other')], default='other', help_text='Skill category for grouping', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of the skill')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark popular skills for quick selection')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='recruiter_s_categor_4ab443_idx'), models.Index(fields=['is_popular'], name='recruiter_s_is_popu_a372e1_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='posts', to='recruiter.skill'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Select your skills', related_name='applicants', to='recruiter.skill'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='recruiter_c_email_c8f515_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_active'], name='recruiter_c_user_ty_9f6067_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='recruiter_c_post_id_677fba_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'created_at'], name='recruiter_c_user_id_18c43a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'applied_at'], name='recruiter_a_status_8738c7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='recruiter_a_job_id_436a21_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'job'), name='unique_application_per_applicant_job'),
        ),
        migrations.AddConstraint(
            model_name='representativeprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('company', 'is_primary_contact'), name='unique_primary_contact_per_company'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'submitted_at'], name='recruiter_p_status_bc3fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['project', 'status'], name='recruiter_p_project_754262_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('applicant', 'project'), name='unique_proposal_per_applicant_project', violation_error_message='You have already submitted a proposal for this project'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='proposal_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'status', 'is_active'], name='recruiter_p_post_ty_4e02fa_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['company', 'status'], name='recruiter_p_company_4cb55c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', 'is_active'], name='recruiter_p_is_feat_60f700_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['experience_years'], name='recruiter_a_experie_2c19cc_idx'),
        ),
    ]
