# Generated by Django 5.2.8 on 2026-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted')], db_index=True, default='applied', max_length=20),
        ),
    ]
